language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t vincentwong/simpleweb -f Dockerfile.dev .

script:
  - docker run -e CI=true vincentwong/simpleweb npm run test -- --coverage
