language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t vincentwong/simpleweb -f Dockerfile.dev .

script:
  - docker run -e CI=true vincentwong/simpleweb npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "simpleweb"
  env: "Simpleweb-env"
  bucket_name: "elasticbeanstalk-us-east-1-400399143602"
  bucket_path: "simpleweb"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
